Create Basic OmF/OmA Maps
kevindougherty-noaa/PyGSI pull request #108
Opened 2021-11-17 21:07 UTC by CoryMartin-NOAA

Closes #96 

This adds a new type of plot, `map departures`, which will plot O-F or O-A (depending on YAML) for the specified domains and variables.

It computes the vmin/vmax based off of the max/min values and is always centered on 0, and also annotates the nobs, min, max on the figure.

Two examples are attached.
<img width="1031" alt="Screen Shot 2021-11-17 at 3 54 37 PM" src="https://user-images.githubusercontent.com/6354668/142282487-f642a9a0-0613-4483-bb32-0ca6735dbe24.png">
<img width="1055" alt="Screen Shot 2021-11-17 at 3 57 14 PM" src="https://user-images.githubusercontent.com/6354668/142282489-e27256d0-74f1-4665-a2ef-4d90d05c066a.png">

2021-11-17 21:22 UTC, kevindougherty-noaa requested changes
Looks great, just one minor comment.

2021-11-17 21:22 UTC, kevindougherty-noaa commented on LAMDA/map_departures.py
> +            'max': maxval,
Can you use `np.round()` to maybe 3 or 4 decimal places?

2021-11-17 21:24 UTC, JacobCarley-NOAA requested changes
Maps look good. Some marks are hard to see when values are small. Suggest adding nonzero line thickness to the marker (circle) edges to make the locations of each observation more clear.

2021-11-17 21:45 UTC, CoryMartin-NOAA commented on LAMDA/map_departures.py
> +            'max': maxval,
Good idea, will do so in the next commit.

2021-11-17 22:23 UTC, JacobCarley-NOAA commented on LAMDA/map_departures.py
> +        omfscatter.markersize = 2
Possible to add the following kwarg? `omfscatter.linewidths=0.15`. I don't know API from which MapScatter is derived, but assuming it's from matplotlib and is based upon `matplotlib.pyplot.scatter` that should help the markers show up a little bit better. If it doesn't work right we made need to change the edgecolor kwarg.

2021-11-17 22:26 UTC, CoryMartin-NOAA commented on LAMDA/map_departures.py
> +        omfscatter.markersize = 2
I think this is something we will have to add to EMCPy, as I don't think all **kwargs are inherited. We probably have to add it, what do you think @kevindougherty-noaa ?

2021-11-17 22:28 UTC, kevindougherty-noaa commented on LAMDA/map_departures.py
> +        omfscatter.markersize = 2
Yes, I was just about to comment on this. Taking a look at [MapScatter](https://github.com/NOAA-EMC/emcpy/blob/develop/src/emcpy/plots/map_plots.py#L1), I think it would be just as simple as adding `self.linewidths` as an additional argument.

2021-11-17 22:29 UTC, CoryMartin-NOAA commented on LAMDA/map_departures.py
> +        omfscatter.markersize = 2
I think this needs even more work in EMCPy, as I don't think the edge colors argument is passed properly, see https://github.com/NOAA-EMC/emcpy/issues/80

2021-11-18 14:19 UTC, CoryMartin-NOAA commented
@JacobCarley-NOAA thoughts? I think this now makes the line edges dominate the plot instead of the fill colors:
<img width="1054" alt="Screen Shot 2021-11-18 at 9 18 05 AM" src="https://user-images.githubusercontent.com/6354668/142432490-75794328-78a4-4d27-b93c-629b2ab7687e.png">
<img width="1019" alt="Screen Shot 2021-11-18 at 9 19 37 AM" src="https://user-images.githubusercontent.com/6354668/142432666-f28bb380-f435-43ee-80b8-5bee06dac665.png">

2021-11-18 14:28 UTC, kevindougherty-noaa commented
@CoryMartin-NOAA I agree it kind of takes away from the colors. Also, this is not an issue on your end, but it looks like CONUS domain is using a 110m coastline and 50m states. Will have to figure that out in EMCPy how to handle that better.

2021-11-18 14:56 UTC, JacobCarley-NOAA commented
@CoryMartin-NOAA Yeah. You and @kevindougherty-noaa are right. I'm kind of surprised to be honest. No edges is definitely preferable over this. 

Overall this is pretty minor.

2021-11-18 17:07 UTC, JacobCarley-NOAA approved these changes

2021-11-18 19:05 UTC, CoryMartin-NOAA commented
@kevindougherty-noaa do you approve the PR now? You requested changes earlier.

2021-11-18 19:15 UTC, kevindougherty-noaa approved these changes
Yes, my apologies. Looks great!

2021-11-18 19:16 UTC, merged