Feature/pandas diags
kevindougherty-noaa/PyGSI pull request #42
Opened 2021-03-04 18:45 UTC by kevindougherty-noaa

Added pandas to diags.py classes to allow for much better readability and better understanding on how indexing works for future users. I will be adding changes to each class in this order: Conventional, Radiance, Ozone.

2021-03-04 19:25 UTC, CoryMartin-NOAA commented on pyGSI/diags.py
> -    def _get_idx_conv(self, obsid=None, subtype=None, station_id=None, analysis_use=False):
Why was analysis_use removed here? I don't necessarily see it as a problem but want to know your reasoning.

2021-03-04 19:32 UTC, kevindougherty-noaa commented on pyGSI/diags.py
> -    def _get_idx_conv(self, obsid=None, subtype=None, station_id=None, analysis_use=False):
So my reasoning is that it makes it easier and cleaner to do pressure indexing. When trying to create the binning with assimilated and monitored data, it was difficult to assign which was which when only given one dataframe in _pressure_indexing(). Makes it much easier to do the pressure indexing across just regular data, lat/lon, and pressure data.

2021-03-04 19:34 UTC, CoryMartin-NOAA commented on pyGSI/diags.py
> -    def _get_idx_conv(self, obsid=None, subtype=None, station_id=None, analysis_use=False):
What if you don't want to do pressure indexing though? Then can you still do analysis_use? Or not?

2021-03-04 19:47 UTC, aerorahul reviewed
I have some questions on the design of this now that dataframes are used.
A dataframe object contains all the info of a diag file and so it is very easy to find the data by just keying in the key.
We probably don't need a lot of the if-else to return data.

if you want a method to get the data, it can be as easy as:

```
def get_data_from_dataframe(df, key):
    try:
           data = df['key']
    except:
            raise KeyValueError('dataframe does not contain {key}')
      return data
```

Thoughts.

2021-03-04 19:47 UTC, kevindougherty-noaa commented on pyGSI/diags.py
> -    def _get_idx_conv(self, obsid=None, subtype=None, station_id=None, analysis_use=False):
Oh I see. Analysis_use is still addressed in lines 210-212 in get_data().
```
if analysis_use:
    assimilated_df = indexed_df.loc[df['Analysis_Use_Flag'] == 1]
    monitored_df = indexed_df.loc[df['Analysis_Use_Flag'] == -1]
```

2021-03-04 19:49 UTC, CoryMartin-NOAA commented on pyGSI/diags.py
> -    def _get_idx_conv(self, obsid=None, subtype=None, station_id=None, analysis_use=False):
ok got it.

2021-03-04 19:53 UTC, CoryMartin-NOAA commented
@aerorahul makes a good point, but I would think we still want some level of abstraction between the raw variable names and what the user is looking for, like 'u_Obs_Minus_Forecast_adjusted' is annoying to type when you can just have the user as for OmF, or whatever.

2021-03-04 19:54 UTC, kevindougherty-noaa commented on pyGSI/diags.py
> +                v = indexed_df['v_Obs_Minus_Forecast_adjusted'].to_numpy()
`.to_numpy() ` returns the data as an array, staying consistent with the original code and not creating issues with plotting/spatial bin scripts

2021-03-04 19:54 UTC, aerorahul reviewed
Also, the point of using pandas is to minimize using variables.  One should be able to access the variables from the dataframe object directly.
When one needs subset of variables, create a new dataframe so that one maintains the structure and that allows one to use indices from one dataframe onto another.

2021-03-04 19:54 UTC, CoryMartin-NOAA commented on pyGSI/diags.py
>              return data
Yeah perhaps a dictionary of key, value pairs that can take the cloud_fraction string from before and 'translate' it to the 'Cloud_Frac' name used in the GSI diag?

2021-03-04 19:56 UTC, aerorahul commented
> @aerorahul makes a good point, but I would think we still want some level of abstraction between the raw variable names and what the user is looking for, like 'u_Obs_Minus_Forecast_adjusted' is annoying to type when you can just have the user as for OmF, or whatever.

if you do that, you made a copy of the data.
Not to mention, OmF is ambiguous in this case as it does not say adjusted, which is what the user extracted.
May be the dataframe itself can be renamed from `u_Obs_Minus_Forecast_adjusted` to something short.  
ps. what is `u_` and why?

2021-03-04 19:57 UTC, kevindougherty-noaa commented
I agree with both of you. Rahul, I think that is great idea to git rid of all the if/else statements now that we have the dataframe. Cory, I still think it is also important to keep the variables simple i.e. 'omf', 'hofx' etc.

2021-03-04 19:59 UTC, CoryMartin-NOAA commented
if we can rename them easily enough in the data frame, then I support that approach.

@aerorahul u is the eastward wind component ;-)

2021-03-04 20:01 UTC, aerorahul commented on pyGSI/diags.py
> +                v = indexed_df['v_Obs_Minus_Forecast_adjusted'].to_numpy()
you should not need that at all.
if you need this at the time of plotting etc call this method where needed and eventually remove it.
I don't recall having to use it anywhere when I was doing binning/plotting/averaging etc.

2021-03-04 20:04 UTC, aerorahul commented on pyGSI/diags.py
>              return data
If I recall, these are keys coming directly from xarray reading of the netcdf file.
I don't know if we want to create mappings of what is in the file to what is "convenient".  It just creates confusion.
WYSIWYG. Agreed those keys are a bit long, but we put them there.  We could have used `long_name` in the netcdf to describe the variable attribute.

2021-03-04 20:05 UTC, aerorahul commented
> if we can rename them easily enough in the data frame, then I support that approach.
> 
> @aerorahul u is the eastward wind component ;-)

I thought it was some unicode character being added.  I've been away from this far too long.

2021-03-04 20:05 UTC, CoryMartin-NOAA commented on pyGSI/diags.py
>              return data
I'm 90% confident there is no long_name attribute for these files...

2021-03-04 20:07 UTC, CoryMartin-NOAA commented
Every other observation is just observation_... but uv has u_observation and v_observation, so they have to be handled separately.

2021-03-04 20:09 UTC, aerorahul commented
Another thing that we can do is break the original dataframe into multiple ones.
e.g.
a dataframe for OmF, OmA OmF_adjusted etc.
They all will have the same indices and columns.

so when you call `OmF['u']` it is the `u_Observation_minus Forecast` and so on.

where can I find a netcdf diag file and load it?  Can someone point to one on Orion.

2021-03-04 20:12 UTC, aerorahul commented
> @aerorahul makes a good point, but I would think we still want some level of abstraction between the raw variable names and what the user is looking for, like 'u_Obs_Minus_Forecast_adjusted' is annoying to type when you can just have the user as for OmF, or whatever.

how else would you do:
```
u = get_data_from_dataframe(df, 'u_Obs_Minus_Forecast_adjusted')
```
you have to type the whole thing somewhere, unless you renamed `u_Obs_Minus_Forecast_adjusted` to `u_OmF_adj` right after populating the dataframe.

2021-03-04 20:14 UTC, CoryMartin-NOAA commented
On Orion, /work/noaa/da/Cory.R.Martin/noscrub/GFS_sample/gdas.20200328/12/diag_conv_uv_ges.2020032812.nc4

Well, before, to the user, this was transparent, they just ask for OmF, the full string is only typed once, when the PyGSI API is created.

2021-03-16 18:21 UTC, aerorahul requested changes
some comments.
I don't quite understand what `indexed_df` is?  It is already indexed when read in in `_read_obs` function.

2021-03-16 18:21 UTC, aerorahul commented on pyGSI/diags.py
> +        diag_type = 'omf' if diag_type in ['omf', 'o-f', 'omb', 'o-b', 'o-a', 'oma'] else diag_type
This is not an appropriate use of the ternary conditional operator where the else is the same as the LHS.

2021-03-16 18:21 UTC, aerorahul commented on pyGSI/diags.py
> +    def _query_diag_type(self, diag_type, df, bias_correction=False):
`_query_diag_type` indicates it is a private method and yet it is explicitly called from a sub-class.

2021-03-16 18:21 UTC, aerorahul commented on pyGSI/diags.py
> +    def _query_diag_type(self, diag_type, df, bias_correction=False):
It is also returning the data not just setting diag_type.

2021-03-16 18:21 UTC, aerorahul commented on pyGSI/diags.py
> +        # Covert byte strings to strings
Not covert

2021-03-16 18:21 UTC, aerorahul commented on pyGSI/diags.py
>              station_id = None
you don't need it at all.
The defaults are provided at the function interface.

2021-03-16 18:32 UTC, kevindougherty-noaa commented on pyGSI/diags.py
> +    def _query_diag_type(self, diag_type, df, bias_correction=False):
Thank you for catching that. Do you suggest renaming it `return_diag_type_data()` or something along those lines to be more descriptive?

2021-03-16 18:32 UTC, kevindougherty-noaa commented on pyGSI/diags.py
>              station_id = None
I see now. Pandas handles better if for example obsid = [None] which can happen if using a YAML compared to the previous version written.

2021-03-16 18:43 UTC, kevindougherty-noaa commented on pyGSI/diags.py
> +        diag_type = 'omf' if diag_type in ['omf', 'o-f', 'omb', 'o-b', 'o-a', 'oma'] else diag_type
> some comments.
> I don't quite understand what `indexed_df` is? It is already indexed when read in in `_read_obs` function.

I guess my wording is not great. The df is made into a multiindexed df in the `read_obs` method by the columns in the list. The indexed_df is the df where all of the inputs by the user (obsid, subtype, station_id) are valid. I should probably change the method name because I am not returning the index of where these are valid like the original script was, I am now returning the already valid dataframe (`indexed_df`). Please let me know if that makes sense.

2021-03-16 18:52 UTC, aerorahul commented on pyGSI/diags.py
> +                    diag_type, indexed_df, bias_correction)
what is `indexed_df` and where is it coming from in this method?

2021-03-16 18:53 UTC, CoryMartin-NOAA commented
@kevindougherty-noaa there are conflicts, need to merge in 'main' to your branch after the changes Xiaoyan added.

2021-03-16 18:57 UTC, kevindougherty-noaa commented on pyGSI/diags.py
> +                    diag_type, indexed_df, bias_correction)
That is a copy and paste mistake. Should be assimilated_df and monitored_df respectively which is called just above. Changing now.

2021-03-16 19:24 UTC, aerorahul commented on pyGSI/diags.py
> +            lats = {'assimilated': assimilated_pressure_df['latitude'],
what is `assimilated_pressure_df` and `monitored_pressure_df`

2021-03-16 19:25 UTC, aerorahul commented
@kevindougherty-noaa 
There are several issues in this PR that need a careful check before it is really reviewable.

2021-03-16 19:59 UTC, CoryMartin-NOAA reviewed
Some initial comments from me as well.

2021-03-16 19:59 UTC, CoryMartin-NOAA commented on pyGSI/diags.py
> +    def _query_diag_type(self, diag_type, df, bias_correction=False):
Why does it need to include 'diag type'? It's part of the class, so can't it just be 'get_data' or something like that?

2021-03-16 19:59 UTC, CoryMartin-NOAA commented on pyGSI/diags.py
> +        diag_type = 'omf' if diag_type in ['omf', 'o-f', 'omb', 'o-b', 'o-a', 'oma'] else diag_type
He's saying you have diag_type here too many times (I think).
It needs to be:
diag_type = 'omf' if DiagType in [...] else diag_type

I think.

Because it will overwrite diag_type's previous value with what is in the list.

2021-03-16 19:59 UTC, CoryMartin-NOAA commented on pyGSI/diags.py
> +        # Covert byte strings to strings
Well those byte strings are sneaky

2021-03-16 19:59 UTC, CoryMartin-NOAA commented on pyGSI/diags.py
> +    def _query_diag_type(self, diag_type, df, bias_correction=False):
So I see get_data is below. Is this to get the entire array of input data and the latter one is the requested subset? Perhaps this is better as combined all together? Pass diag_type to the get_data routine?

2021-03-16 19:59 UTC, CoryMartin-NOAA commented on pyGSI/diags.py
> +            lats = {'assimilated': assimilated_pressure_df['latitude'],
Yeah I have the same question, where are they defined? I don't see them as input to the function.

2021-03-17 15:48 UTC, kevindougherty-noaa commented on pyGSI/diags.py
> +    def _query_diag_type(self, diag_type, df, bias_correction=False):
The reason we do not combine the two is because the current `query_diag_type()` applies to all classes eventually, but right now I am only focusing on making changes to `Conventional()`. The name of the method needs to change because we used to literally query through all different diag types. Now with the pandas df, we can just use the diag_type name to extract the correct subsetted column from the dataframe. I will rename the method to reflect what it does now more accurately.

2021-03-18 20:07 UTC, CoryMartin-NOAA reviewed
A few comments/questions.

2021-03-18 20:07 UTC, CoryMartin-NOAA commented on pyGSI/diags.py
> +        except:
Why is this wrapped in a try, except and then an if? why not just raise exception in the else? Am I missing something?

2021-03-18 20:07 UTC, CoryMartin-NOAA commented on pyGSI/diags.py
> +            indx = df.index.get_level_values('Observation_Type') == ''
Is this first one just so the loop doesn't error on the first iteration?

2021-03-18 20:15 UTC, kevindougherty-noaa commented on pyGSI/diags.py
> +                except:
It's more or less just tries to grab the column if it is omf and including the bias variable in the column, otherwise it does not include the bias variable. I understand what you are saying though and can figure out what type of error occurs if column does not exist. This helps to eliminate things like if omf, do something else other variable, do something.

2021-03-18 20:17 UTC, kevindougherty-noaa commented on pyGSI/diags.py
> +        except:
It is wrapped like this in the case the user inputs a diag_type that does not make sense. i.e. diag_type = 'blah'

2021-03-18 20:19 UTC, CoryMartin-NOAA commented on pyGSI/diags.py
> +                except:
Yeah, my point was what you have is fine, but what if there is some other sort of error that we want to cause it to fail. 'except' should generally only be explicit (and can be multiple types, I forget the exact syntax though of how to do that)

2021-03-18 20:21 UTC, CoryMartin-NOAA commented on pyGSI/diags.py
> +        except:
Ok I see, so this is an excellent illustration of my earlier point, then this should be 'except KeyError' or something similar.

2021-03-18 20:29 UTC, kevindougherty-noaa commented on pyGSI/diags.py
> +            indx = df.index.get_level_values('Observation_Type') == ''
This was taken from Rahul's code that he shared. It returns an array of all booleans that are False, then loops through every input of the variable and finds where the variable is true and replaces the index with that index. That way, if there is no cases of that variable, the index remains all false and is applied to the dataframe. That way, if one of the inputs does not exist, the dataframe will return as empty.

2021-03-18 20:43 UTC, kevindougherty-noaa commented on pyGSI/diags.py
> +                except:
Got it. tested it out and it was KeyError so I will include that in next commit.

2021-03-18 20:58 UTC, aerorahul commented on pyGSI/diags.py
> +    def get_diag_type_data(self, diag_type, df, bias_correction=False):
why do we need df? Isn't `data_df` and attribute of the object?

2021-03-18 20:59 UTC, aerorahul commented on pyGSI/diags.py
> +        except:
if a user inputs a `blah` diag_type, it should never get here.

2021-03-18 22:09 UTC, aerorahul commented
I am thinking if we can have a way to hide the 'if-else' with regards to uv and everything else

2021-03-18 22:12 UTC, aerorahul commented on pyGSI/diags.py
> +            indx = df.index.get_level_values('Observation_Type') == ''
@kevindougherty-noaa is correct in explaining why the first line "initializes" the search locations to empty.  In the end, if there are no matches, it will return nothing.  That is the point of 'selecting' data based on search criteria.

2021-03-19 14:45 UTC, kevindougherty-noaa commented on pyGSI/diags.py
> +    def get_diag_type_data(self, diag_type, df, bias_correction=False):
yes, but when selecting data, if analysis_use=True, `_select_conv()` returns assimilated_df and monitored_df. So unless we address analysis_use in `get_diag_tyep_data()`, we need df

2021-10-12 18:52 UTC, CoryMartin-NOAA commented
This is really old, closing.

2021-10-12 18:52 UTC, closed without merging