Feature/return df
kevindougherty-noaa/PyGSI pull request #76
Opened 2021-10-05 18:04 UTC by kevindougherty-noaa

2021-10-05 18:08 UTC, kevindougherty-noaa commented
@CoryMartin-NOAA still need to go through the other files for `pycodestyle` to pass, however `diags.py` passes which is the only file I changed.

2021-10-05 18:20 UTC, CoryMartin-NOAA commented
@kevindougherty-noaa can you explain to @ADCollard and me why this PR is needed? I'm sure it is a method vs attribute thing but it's not clear to me at the moment.

2021-10-05 18:26 UTC, kevindougherty-noaa commented
@CoryMartin-NOAA @ADCollard Sure thing. In our regional DA meeting last week, Ting and Shun mentioned interest in being able to have the entire dataframe returned. I could be mistaken and maybe they meant returning the dataframe after being indexed.

2021-10-05 18:27 UTC, aerorahul requested changes
See comment.

2021-10-05 18:27 UTC, aerorahul commented on pyGSI/diags.py
> +
Why can't you add this method in `Class GSIdiag` since that is the class from which all other inherit from?

2021-10-05 18:29 UTC, CoryMartin-NOAA commented
@kevindougherty-noaa yes I remember that, so I guess you're saying this is so one can have numpy arrays if they want, and a Pandas dataframe through the `.return_df()` method? I thought the issue you linked would basically imply that the read method would have an argument like `read_data(return_df=True)` and then:
```
if return_df:
    return self.df
else:
   return data
```
or whatever the above pseudo code should be

2021-10-05 18:30 UTC, kevindougherty-noaa commented
@CoryMartin-NOAA you are right, that is what should be done. I will fix.

2021-10-05 19:17 UTC, CoryMartin-NOAA commented on pyGSI/diags.py
> +				if return_df:
@kevindougherty-noaa is this indentation correct?

2021-10-05 19:40 UTC, CoryMartin-NOAA commented on pyGSI/diags.py
> +                if return_df:
so for non data frame, it returns a dict of dicts, for u,v. For the data frame case, are both u and v inside the data frame?

2021-10-05 19:53 UTC, kevindougherty-noaa commented on pyGSI/diags.py
> +                if return_df:
Yes, both u and v are in the dataframe. All the variables will be included.

2021-10-06 12:25 UTC, aerorahul requested changes
Just a quick glance. 
See if you notice these as well.

2021-10-06 12:25 UTC, aerorahul commented on pyGSI/diags.py
> +                            indexed_df, diag_type, bias_correction)
```suggestion
                    return self._query_diag_type(
                            indexed_df, diag_type, bias_correction)
```

2021-10-06 12:25 UTC, aerorahul commented on pyGSI/diags.py
> +                        return data
```suggestion
```

2021-10-06 12:30 UTC, CoryMartin-NOAA commented on pyGSI/diags.py
> +                            indexed_df, diag_type, bias_correction)
This is a good suggestion

2021-10-06 13:57 UTC, kevindougherty-noaa commented on pyGSI/diags.py
> +                            indexed_df, diag_type, bias_correction)
I like it, thanks @aerorahul.

2021-10-06 15:03 UTC, kevindougherty-noaa commented
Based on conversations with @CoryMartin-NOAA and @aerorahul, I am going to close this PR and develop `diags.py` to only return dataframes rather than specific variables. It should cut out a good amount of code.

2021-10-06 15:03 UTC, closed without merging